name: CI/CD

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install
        run: |
          pip install -r requirements.txt          

      - name: Run tests
        run: coverage run -m --source=. pytest

      - name: Tests report
        run: |
          coverage report -m 
          coverage xml 
        
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

                    
      - name: Code Coverage Summary 
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '40 80'
      
      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
